name: insta_cap
description: "AI-powered Instagram caption generator with beautiful UI and advanced features"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animations
  cupertino_icons: ^1.0.8
  animate_do: ^3.3.4
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  page_transition: ^2.1.0
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.8
  
  # Glass & UI Effects
  glassmorphism: ^3.0.0
  flutter_glass: ^0.0.8
  glass_kit: ^3.0.0
  backdrop: ^0.9.1
  
  # Typography & Icons
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  iconsax: ^0.0.8
  phosphor_flutter: ^2.0.1
  
  # Navigation & State Management
  go_router: ^12.1.3
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  
  # Networking & API
  http: ^1.1.0
  dio: ^5.3.2
  http_parser: ^4.0.2
  
  # Firebase & Authentication
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_analytics: ^10.7.4
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  google_sign_in: ^6.2.1
  
  # Local Storage & Database
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Image Handling
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_image_compress: ^2.3.0
  image_cropper: ^8.0.1
  photo_view: ^0.15.0
  path_provider: ^2.1.4
  
  # UI Components
  flutter_screenutil: ^5.9.3
  # fluttertoast: ^8.2.6  # Removed due to Kotlin compilation issues
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.2
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Security & Storage
  flutter_secure_storage: ^9.2.2
  
  # Pull to refresh
  pull_to_refresh: ^2.0.0
  
  # Additional Features
  clipboard: ^0.1.3
  rive: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  

